### ISSUE TITLE
frames/borders missing on who-we work wih

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#7]
![frames](https://cloud.githubusercontent.com/assets/9592326/10149296/e7b4bf82-6638-11e5-936e-ac9e16cda01f.JPG)

according to design there shouldbe frames/borders between different case studies. 
view case studies link below logo/picture is not shown according to designs.

**Comment by codephobe** [comment]
Yes, the borders haven't been displayed. That's because if they want the shuffling and filter animation to be achieved, the layout doesn't function well on window resize and each row will have 3 elements instead of four (margin overlap). Compromised by removing the borders to achieve a look closest to the design within the plugin constraints.
